### PR TITLE
MTL-1628 Support both runtime and initrd lib loads

### PR DESCRIPTION
**Pull request by rustydb**
#### Summary and Scope

- Fixes MTL-1628
- Relates to CASMTRIAGE-3025 (discovered and created as tangental work during this JIRA's investigation).

##### Issue Type

- RFE Pull Request

Previously this was sourcing the dracut-lib.sh file from a specific
location that only exists in the initrd. Now this will smartly
source it from its runtime location or its initrd location
depending on which one exists.

Also tidies up the commented areas, make them consistent.

Adds:
- `metal_fsopts_xfs` for globally defining our FSopts for XFS.
- `metal_fstab` for globally defining the location of our new fstab file.
- `metal_disk_small` for globally defining a small disk size.
- `metal_disk_large` for globally defining a large disk size.

Some new functions were added:
- `metal_scand` takes an offset and finds disks for resolution by `metal_resolve_disk`.
- `_load_dracut_dep` runs in `metal-lib.sh`, even when sourced. Ensures that dracut-lib is loaded whether metal-lib.sh is loaded in Linux runtime or within the initrd context.

#### Prerequisites

- [x] I have included documentation in my PR (or it is not required)
- [x] I tested this on internal system (x) (if yes, please include results or a description of the test)
 
> redbull
1. storage-ceph nodes booted with dracut-metal-mdsquash
2. ceph deployed from bare-metal

#### Risks and Mitigations
 
What is less risky, or more risky now - or if your mod fails is there a new risk?

This enhances the dracut-metal codebase by providing functions and constants in a global library instead of:
- 3 different `lsblk` commands; each dracut-metal module had a duplicate or special `lsblk` command
- Redefinitions of `/etc/fstab.metal`
- Redefinitions of the `fsopts` used for XFS

### CODE REVIEW

**Comment by rustydb** [comment]
Example output from `metal-disks=2` and the new call to `metal_scand`:

```bash
 Warning: Found the following disks for the main RAID array (qty. [2]): [sda sdb]
```

**Comment by rustydb** [comment]
Merging after I return from leave.

**Review by heemstra — APPROVED** [review]

**Review by jacobsalmela — APPROVED** [review]
We should also come back to these in another PR and fixup the `shellcheck` warnings.

**Comment by rustydb** [comment]
> We should also come back to these in another PR and fixup the `shellcheck` warnings.

we should probably run shellcheck on native-dracut too.. worthwhile to see if it is worthwhile.

**Pull request merged**
